repos:
  - repo: local
    hooks:      
      - id: autoflake
        name: autoflake
        entry: pipenv run autoflake 
        language: python
        types: [python]        
        args:
          - "--in-place"
          - "--expand-star-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"  
          - "--remove-all-unused-imports"    
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python] 
      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py  
  