version: '3.8'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  app:
    build: ./app
    volumes:
      - ./app:/app
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./app/static:/app/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8000:80
    depends_on:
      - app

  etl:
    build: ./etl
    volumes:
      - ./etl:/etl
    env_file:
      - ./.env
    depends_on:
      - nginx

volumes:
  postgres_data:


