version: "3.8"
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - ./db/backup-08-02-2023.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./db/.env
  app:
    build:
      context: ./app
      dockerfile: Dockerfile   
    volumes:         
      - ./app:/app
    expose:
      - 8000
    env_file:
      - ./app/.env
    depends_on:
      - db
  nginx: 
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro         
      - ./app/static:/app/static
    depends_on:
      - app
    ports:
      - 8000:80
volumes:
  postgres_data:  