version: "3.8"
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - ./db/backup-08-02-2023.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    build:
      context: ./app
      dockerfile: Dockerfile   
    volumes:         
      - ./app:/app
    expose:
      - ${EXPOSE_PORT}
    env_file:
      - .env
    depends_on:
      - db
  nginx: 
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro         
      - ./app/static:/app/static
    depends_on:
      - app
    ports:
      - ${EXPOSE_PORT}:80
    elasticsearch:    
      image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
      environment:
        - xpack.security.enabled=false
        - "discovery.type=single-node"
      networks:
        - es-net
      ports:
        - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
volumes:
  postgres_data:  