version: '3.8'
services:
  db:    
    image: postgres:15     
    volumes:    
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  app:
    build: ./app     
    volumes:
      - ./app:/app 
      - static_volume:/app/static 
    expose:
      - 8000    
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx    
    volumes:
      - static_volume:/app/static:ro
      - ./nginx/nginx.conf:/nginx/nginx.conf:ro
    ports:
      - 8000:80
    depends_on:
      - app

  etl:
    build: ./etl       
    volumes:
      - ./etl:/etl        
    env_file:
      - ./.env
    depends_on:
      - nginx

volumes:
  postgres_data: 
  static_volume:
