version: "3.8"
services:
  db:
    image: postgres:15
    volumes:
      - ./db/backup-08-02-2023.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.dev

  # es:    
  #   image: elasticsearch:7.17.9
  #   environment:     
  #     - xpack.security.enabled=false 
  #     - "discovery.type=single-node" 
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data 
  #   env_file:
  #     - .env.dev  
  #   ports:
  #     - 9200:9200   

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev  
    volumes:         
      - ./app:/app
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - es

  nginx: 
    image: nginx:1.21.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro         
      - ./app/static:/app/static
    depends_on:
      - app
    ports:
      - 8000:80  

volumes:
  postgres_data:
  es_data:
    driver: local

