version: "3.8"
services:
  db:
    image: postgres:15
    volumes:
      - ./db/backup-08-02-2023.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.dev
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev  
    volumes:         
      - ./app:/app
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db
  nginx: 
    image: nginx:1.21.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro         
      - ./app/static:/app/static
    depends_on:
      - app
    ports:
      - 8000:80
volumes:
  postgres_data: