# base image
FROM python:3.8

# enviironment variables
ENV HOME=/
ENV APP_HOME=/app
ENV GROUP=django

# create app directory
WORKDIR $APP_HOME

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE 'config.settings'

RUN apt-get update && apt-get install -y gettext && apt install -y ncat
RUN python -m pip install --upgrade pip

COPY Pipfile Pipfile.lock ./
RUN pip install pipenv && pipenv install --system --dev

COPY . $APP_HOME

EXPOSE 8000

RUN chmod +x ./docker-entrypoint.dev.sh

ENTRYPOINT ["./docker-entrypoint.dev.sh"]